---
title: "02_clean"
format: html
editor: visual
---

In this file, we take the raw data we have in the *data* folder, and we clean it from NAs.

## Loading libraries

```{r}
#| message: false
library("tidyverse")
```

## Loading data

```{r}
#first_path <- "/net/pupil1/home/people/s242150/projects/R_project"
#first_path <- "/net/pupil1/home/people/s243057/projects/R_project"
first_path <- "~/projects/R_project"
file_path <- file.path(first_path, "data/01_dat_load.tsv")
df <- read_tsv(file = file_path)
```

## Cleaning data

```{r}
proteins <- df |>
  select(2:78) |>
  names()

classes <- df |>
  distinct(class) |>
  pull(class)
```

Checking how many missing values appear in each column.

```{r}
missing_summary <- colSums(is.na(df))
print(missing_summary)
```

Replacing the missing data (NaN) with mean values within each class

```{r}
df <- as.data.frame(df)

df_mean <- df |>
  group_by(class) |>
  mutate(across(everything(),
                ~ ifelse(is.na(.),
                         mean(., na.rm = TRUE), .))) |>
  ungroup()

missing_summary <- colSums(is.na(df_mean))

print(missing_summary)
```

## Reshape data for visualization

```{r}
df_long <- df |>
  pivot_longer(cols = c(H3MeK4_N, 
                      EGR1_N, 
                      H3AcK18_N, 
                      BCL2_N, 
                      pCFOS_N, 
                      BAD_N),
             names_to = "Protein", 
             values_to = "Expression")

df_mean_long <- df_mean |>
  pivot_longer(cols = c(H3MeK4_N, 
                        EGR1_N, 
                        H3AcK18_N, 
                        BCL2_N, 
                        pCFOS_N, 
                        BAD_N),
               names_to = "Protein", 
               values_to = "Expression")

# Combine all datasets for comparison 

df_compare <- df_long |>
  mutate(Method = "Original") |>
  bind_rows(
    df_mean_long |>
      mutate(Method = "Mean Replacement")
    )

# Plot density
ggplot(data = df_compare, 
       mapping = aes(x = Expression, 
                     fill = Method)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~Protein, 
             scales = "fixed") +
  theme_minimal() +
  labs(title = "Distribution of Protein Expression After Replacements",
       x = "Expression Level",
       y = "Density")
```

Writing the cleaned .tsv file in the *data* folder:

```{r}
file_path <- "data/02_dat_clean.tsv"
file_path <- file.path(first_path, file_path)

df <- df_mean

df |>
  write_tsv(file = file_path)
```
